name = "cf-panel"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改

id = "01cec9bf3129418f834133188e75af9e"				#KV数据库id

